# Generated by Django 5.0.6 on 2024-06-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewgadget',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
    ]
