# Generated by Django 5.0.6 on 2024-06-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_comment_remove_reviewgadget_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewgadget',
            old_name='start',
            new_name='stars',
        ),
    ]
